# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adkevin3307/Data/Projects/body_isosurface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adkevin3307/Data/Projects/body_isosurface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adkevin3307/Data/Projects/body_isosurface/CMakeFiles /home/adkevin3307/Data/Projects/body_isosurface//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adkevin3307/Data/Projects/body_isosurface/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/adkevin3307/Data/Projects/body_isosurface/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/BufferManagement.o: src/BufferManagement.cpp.o
.PHONY : src/BufferManagement.o

# target to build an object file
src/BufferManagement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/BufferManagement.cpp.o
.PHONY : src/BufferManagement.cpp.o

src/BufferManagement.i: src/BufferManagement.cpp.i
.PHONY : src/BufferManagement.i

# target to preprocess a source file
src/BufferManagement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/BufferManagement.cpp.i
.PHONY : src/BufferManagement.cpp.i

src/BufferManagement.s: src/BufferManagement.cpp.s
.PHONY : src/BufferManagement.s

# target to generate assembly for a file
src/BufferManagement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/BufferManagement.cpp.s
.PHONY : src/BufferManagement.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/IsoSurface.o: src/IsoSurface.cpp.o
.PHONY : src/IsoSurface.o

# target to build an object file
src/IsoSurface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/IsoSurface.cpp.o
.PHONY : src/IsoSurface.cpp.o

src/IsoSurface.i: src/IsoSurface.cpp.i
.PHONY : src/IsoSurface.i

# target to preprocess a source file
src/IsoSurface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/IsoSurface.cpp.i
.PHONY : src/IsoSurface.cpp.i

src/IsoSurface.s: src/IsoSurface.cpp.s
.PHONY : src/IsoSurface.s

# target to generate assembly for a file
src/IsoSurface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/IsoSurface.cpp.s
.PHONY : src/IsoSurface.cpp.s

src/MeshManagement.o: src/MeshManagement.cpp.o
.PHONY : src/MeshManagement.o

# target to build an object file
src/MeshManagement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MeshManagement.cpp.o
.PHONY : src/MeshManagement.cpp.o

src/MeshManagement.i: src/MeshManagement.cpp.i
.PHONY : src/MeshManagement.i

# target to preprocess a source file
src/MeshManagement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MeshManagement.cpp.i
.PHONY : src/MeshManagement.cpp.i

src/MeshManagement.s: src/MeshManagement.cpp.s
.PHONY : src/MeshManagement.s

# target to generate assembly for a file
src/MeshManagement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/MeshManagement.cpp.s
.PHONY : src/MeshManagement.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Slice.o: src/Slice.cpp.o
.PHONY : src/Slice.o

# target to build an object file
src/Slice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Slice.cpp.o
.PHONY : src/Slice.cpp.o

src/Slice.i: src/Slice.cpp.i
.PHONY : src/Slice.i

# target to preprocess a source file
src/Slice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Slice.cpp.i
.PHONY : src/Slice.cpp.i

src/Slice.s: src/Slice.cpp.s
.PHONY : src/Slice.s

# target to generate assembly for a file
src/Slice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Slice.cpp.s
.PHONY : src/Slice.cpp.s

src/Transformation.o: src/Transformation.cpp.o
.PHONY : src/Transformation.o

# target to build an object file
src/Transformation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Transformation.cpp.o
.PHONY : src/Transformation.cpp.o

src/Transformation.i: src/Transformation.cpp.i
.PHONY : src/Transformation.i

# target to preprocess a source file
src/Transformation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Transformation.cpp.i
.PHONY : src/Transformation.cpp.i

src/Transformation.s: src/Transformation.cpp.s
.PHONY : src/Transformation.s

# target to generate assembly for a file
src/Transformation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Transformation.cpp.s
.PHONY : src/Transformation.cpp.s

src/Volume.o: src/Volume.cpp.o
.PHONY : src/Volume.o

# target to build an object file
src/Volume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Volume.cpp.o
.PHONY : src/Volume.cpp.o

src/Volume.i: src/Volume.cpp.i
.PHONY : src/Volume.i

# target to preprocess a source file
src/Volume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Volume.cpp.i
.PHONY : src/Volume.cpp.i

src/Volume.s: src/Volume.cpp.s
.PHONY : src/Volume.s

# target to generate assembly for a file
src/Volume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Volume.cpp.s
.PHONY : src/Volume.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/imgui/imgui.o: src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.o

# target to build an object file
src/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.cpp.o

src/imgui/imgui.i: src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.i

# target to preprocess a source file
src/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.cpp.i

src/imgui/imgui.s: src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.s

# target to generate assembly for a file
src/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.cpp.s

src/imgui/imgui_demo.o: src/imgui/imgui_demo.cpp.o
.PHONY : src/imgui/imgui_demo.o

# target to build an object file
src/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_demo.cpp.o
.PHONY : src/imgui/imgui_demo.cpp.o

src/imgui/imgui_demo.i: src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.i

# target to preprocess a source file
src/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.cpp.i

src/imgui/imgui_demo.s: src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.s

# target to generate assembly for a file
src/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.cpp.s

src/imgui/imgui_draw.o: src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.o

# target to build an object file
src/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.cpp.o

src/imgui/imgui_draw.i: src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.i

# target to preprocess a source file
src/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.cpp.i

src/imgui/imgui_draw.s: src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.s

# target to generate assembly for a file
src/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.cpp.s

src/imgui/imgui_impl_glfw.o: src/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/imgui/imgui_impl_glfw.o

# target to build an object file
src/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/imgui/imgui_impl_glfw.cpp.o

src/imgui/imgui_impl_glfw.i: src/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/imgui_impl_glfw.i

# target to preprocess a source file
src/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/imgui_impl_glfw.cpp.i

src/imgui/imgui_impl_glfw.s: src/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
src/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/imgui_impl_glfw.cpp.s

src/imgui/imgui_impl_opengl3.o: src/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui/imgui_impl_opengl3.o

# target to build an object file
src/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui/imgui_impl_opengl3.cpp.o

src/imgui/imgui_impl_opengl3.i: src/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
src/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui/imgui_impl_opengl3.cpp.i

src/imgui/imgui_impl_opengl3.s: src/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui/imgui_impl_opengl3.cpp.s

src/imgui/imgui_stdlib.o: src/imgui/imgui_stdlib.cpp.o
.PHONY : src/imgui/imgui_stdlib.o

# target to build an object file
src/imgui/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_stdlib.cpp.o
.PHONY : src/imgui/imgui_stdlib.cpp.o

src/imgui/imgui_stdlib.i: src/imgui/imgui_stdlib.cpp.i
.PHONY : src/imgui/imgui_stdlib.i

# target to preprocess a source file
src/imgui/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_stdlib.cpp.i
.PHONY : src/imgui/imgui_stdlib.cpp.i

src/imgui/imgui_stdlib.s: src/imgui/imgui_stdlib.cpp.s
.PHONY : src/imgui/imgui_stdlib.s

# target to generate assembly for a file
src/imgui/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_stdlib.cpp.s
.PHONY : src/imgui/imgui_stdlib.cpp.s

src/imgui/imgui_tables.o: src/imgui/imgui_tables.cpp.o
.PHONY : src/imgui/imgui_tables.o

# target to build an object file
src/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_tables.cpp.o
.PHONY : src/imgui/imgui_tables.cpp.o

src/imgui/imgui_tables.i: src/imgui/imgui_tables.cpp.i
.PHONY : src/imgui/imgui_tables.i

# target to preprocess a source file
src/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_tables.cpp.i
.PHONY : src/imgui/imgui_tables.cpp.i

src/imgui/imgui_tables.s: src/imgui/imgui_tables.cpp.s
.PHONY : src/imgui/imgui_tables.s

# target to generate assembly for a file
src/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_tables.cpp.s
.PHONY : src/imgui/imgui_tables.cpp.s

src/imgui/imgui_widgets.o: src/imgui/imgui_widgets.cpp.o
.PHONY : src/imgui/imgui_widgets.o

# target to build an object file
src/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_widgets.cpp.o
.PHONY : src/imgui/imgui_widgets.cpp.o

src/imgui/imgui_widgets.i: src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.i

# target to preprocess a source file
src/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.cpp.i

src/imgui/imgui_widgets.s: src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.s

# target to generate assembly for a file
src/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/BufferManagement.o"
	@echo "... src/BufferManagement.i"
	@echo "... src/BufferManagement.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/IsoSurface.o"
	@echo "... src/IsoSurface.i"
	@echo "... src/IsoSurface.s"
	@echo "... src/MeshManagement.o"
	@echo "... src/MeshManagement.i"
	@echo "... src/MeshManagement.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Slice.o"
	@echo "... src/Slice.i"
	@echo "... src/Slice.s"
	@echo "... src/Transformation.o"
	@echo "... src/Transformation.i"
	@echo "... src/Transformation.s"
	@echo "... src/Volume.o"
	@echo "... src/Volume.i"
	@echo "... src/Volume.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/imgui/imgui.o"
	@echo "... src/imgui/imgui.i"
	@echo "... src/imgui/imgui.s"
	@echo "... src/imgui/imgui_demo.o"
	@echo "... src/imgui/imgui_demo.i"
	@echo "... src/imgui/imgui_demo.s"
	@echo "... src/imgui/imgui_draw.o"
	@echo "... src/imgui/imgui_draw.i"
	@echo "... src/imgui/imgui_draw.s"
	@echo "... src/imgui/imgui_impl_glfw.o"
	@echo "... src/imgui/imgui_impl_glfw.i"
	@echo "... src/imgui/imgui_impl_glfw.s"
	@echo "... src/imgui/imgui_impl_opengl3.o"
	@echo "... src/imgui/imgui_impl_opengl3.i"
	@echo "... src/imgui/imgui_impl_opengl3.s"
	@echo "... src/imgui/imgui_stdlib.o"
	@echo "... src/imgui/imgui_stdlib.i"
	@echo "... src/imgui/imgui_stdlib.s"
	@echo "... src/imgui/imgui_tables.o"
	@echo "... src/imgui/imgui_tables.i"
	@echo "... src/imgui/imgui_tables.s"
	@echo "... src/imgui/imgui_widgets.o"
	@echo "... src/imgui/imgui_widgets.i"
	@echo "... src/imgui/imgui_widgets.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/adkevin3307/Data/Projects/body_isosurface/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

